function tripletStatsLoaderGUI()
% tripletStatsLoaderGUI
%
% Standalone post-processing GUI for MLstructureFinder triplet CSV exports.
%
% Loads the full triplet CSV file generated by "Export triplets", reconstructs
% the same raw feature-statistics array used by Feature statistics, and launches
% a controls GUI that produces:
%
%   1) PDF of l/(x - x0)
%   2) PDF of b/a
%   3) Joint PDF: l/(x - x0) vs b/a
%   4) Joint PDF: l/(x - x0) vs x
%
% This GUI does not read Tecplot flow fields and does not re-run structure
% detection. It only interrogates the exported triplet CSV.

%% ----- state -----
S = struct();
S.cases = {};
S.curCase = 1;

%% ----- loader GUI -----
f = figure('Name','Triplet Statistics Loader', ...
           'NumberTitle','off', ...
           'MenuBar','none', ...
           'ToolBar','none', ...
           'Resize','off', ...
           'Position',[120 120 620 360]);

uicontrol(f,'Style','pushbutton', ...
    'String','Load full triplet CSV...', ...
    'FontSize',10, ...
    'Position',[20 310 180 30], ...
    'Callback',@onLoadCSV);

uicontrol(f,'Style','pushbutton', ...
    'String','Remove selected', ...
    'FontSize',10, ...
    'Position',[220 310 130 30], ...
    'Callback',@onRemoveSelected);

uicontrol(f,'Style','pushbutton', ...
    'String','Clear all', ...
    'FontSize',10, ...
    'Position',[370 310 100 30], ...
    'Callback',@onClearAll);

uicontrol(f,'Style','pushbutton', ...
    'String','Launch statistics GUI', ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Position',[20 260 180 34], ...
    'Callback',@onLaunchStats);

hList = uicontrol(f,'Style','listbox', ...
    'FontSize',10, ...
    'Position',[20 60 580 185], ...
    'String',{}, ...
    'Callback',@onSelectCase);

hInfo = uicontrol(f,'Style','text', ...
    'String','No triplet CSV loaded.', ...
    'FontSize',10, ...
    'HorizontalAlignment','left', ...
    'Position',[20 20 580 25]);

guidata(f,S);

%% ----- callbacks -----
    function onLoadCSV(~,~)
        S = guidata(f);

        [fn,fp] = uigetfile({'*.csv','CSV files (*.csv)';'*.*','All files'}, ...
                            'Select full triplet CSV', ...
                            'MultiSelect','on');

        if isequal(fn,0)
            return;
        end

        if ischar(fn)
            fn = {fn};
        end

        for k = 1:numel(fn)
            fullp = fullfile(fp,fn{k});

            try
                c = readTripletCSV_(fullp);
            catch ME
                warning('Failed to read %s: %s', fullp, ME.message);
                errordlg(sprintf('Failed to read:\n%s\n\n%s',fullp,ME.message), ...
                         'CSV read error');
                continue;
            end

            c.name = makeUniqueCaseName_(S.cases, c.name);
            S.cases{end+1} = c; %#ok<AGROW>

            fprintf('Loaded %s: %d triplets\n', c.name, numel(c.zoneIdx));
        end

        if ~isempty(S.cases)
            S.curCase = numel(S.cases);
        else
            S.curCase = 1;
        end

        guidata(f,S);
        refreshLoaderList();
    end

    function onRemoveSelected(~,~)
        S = guidata(f);

        if isempty(S.cases)
            return;
        end

        idx = get(hList,'Value');
        idx = max(1,min(numel(S.cases),idx));

        S.cases(idx) = [];

        if isempty(S.cases)
            S.curCase = 1;
        else
            S.curCase = max(1,min(numel(S.cases),idx));
        end

        guidata(f,S);
        refreshLoaderList();
    end

    function onClearAll(~,~)
        S = guidata(f);
        S.cases = {};
        S.curCase = 1;
        guidata(f,S);
        refreshLoaderList();
    end

    function onSelectCase(~,~)
        S = guidata(f);

        if isempty(S.cases)
            return;
        end

        S.curCase = get(hList,'Value');
        S.curCase = max(1,min(numel(S.cases),S.curCase));

        guidata(f,S);
        refreshLoaderList();
    end

    function onLaunchStats(~,~)
        S = guidata(f);

        if isempty(S.cases)
            errordlg('Load at least one full triplet CSV first.', ...
                     'Triplet statistics');
            return;
        end

        idx = get(hList,'Value');
        idx = max(1,min(numel(S.cases),idx));

        tripletStatsGUI_(S.cases{idx});
    end

    function refreshLoaderList()
        S = guidata(f);

        if isempty(S.cases)
            set(hList,'String',{},'Value',1);
            set(hInfo,'String','No triplet CSV loaded.');
            return;
        end

        names = cell(numel(S.cases),1);

        for ii = 1:numel(S.cases)
            c = S.cases{ii};
            nAll = numel(c.zoneIdx);
            nLab = sum(c.labelled == 1);
            nAcc = sum(c.accepted == 1);
            nRej = sum(c.accepted == 0);

            names{ii} = sprintf('%s    [%d triplets, %d labelled, %d accepted, %d rejected]', ...
                                c.name,nAll,nLab,nAcc,nRej);
        end

        S.curCase = max(1,min(numel(S.cases),S.curCase));

        set(hList,'String',names,'Value',S.curCase);

        c = S.cases{S.curCase};

        set(hInfo,'String',sprintf('Selected: %s | file: %s', ...
            c.name,c.filename));
    end
end

function c = readTripletCSV_(filename)
% Read a full triplet CSV export and reconstruct feature-stats quantities.
%
% Robust version:
%   - finds the actual CSV header line explicitly
%   - handles files with blank/comment/metadata lines before the header
%   - then reads the table from that header line onward

headerLine = findTripletHeaderLine_(filename);

opts = detectImportOptions(filename, ...
    'FileType','text', ...
    'Delimiter',',', ...
    'VariableNamingRule','preserve', ...
    'NumHeaderLines',headerLine-1);

T = readtable(filename,opts);

varNames = T.Properties.VariableNames;

% Debug print: useful if MATLAB still misreads the file.
fprintf('\nRead CSV header from line %d:\n', headerLine);
for ii = 1:numel(varNames)
    fprintf('  %2d: %s\n', ii, varNames{ii});
end

idxZone = findColumn_(varNames, {'zone'});
idxXL   = findColumn_(varNames, {'x_upstream','xupstream'});
idxYL   = findColumn_(varNames, {'y_upstream','yupstream'}, false);
idxXC   = findColumn_(varNames, {'x_core','xcore'});
idxYC   = findColumn_(varNames, {'y_core','ycore'}, false);
idxXR   = findColumn_(varNames, {'x_downstream','xdownstream'});
idxYR   = findColumn_(varNames, {'y_downstream','ydownstream'}, false);
idxL    = findColumn_(varNames, {'l'});
idxLab  = findColumn_(varNames, {'labelled','labeled'}, false);
idxAcc  = findColumn_(varNames, {'accepted','accept'}, false);

zoneIdx = tableColNumeric_(T, idxZone);
xL      = tableColNumeric_(T, idxXL);
xc      = tableColNumeric_(T, idxXC);
xR      = tableColNumeric_(T, idxXR);

if isempty(idxYL)
    yL = NaN(size(xL));
else
    yL = tableColNumeric_(T, idxYL);
end

if isempty(idxYC)
    yc = NaN(size(xL));
else
    yc = tableColNumeric_(T, idxYC);
end

if isempty(idxYR)
    yR = NaN(size(xL));
else
    yR = tableColNumeric_(T, idxYR);
end

lCSV = tableColNumeric_(T, idxL);

% Prefer geometric l from xR - xL, but retain CSV consistency if needed.
lGeom = xR - xL;
l = lGeom;

badL = ~isfinite(l) | l <= 0;
l(badL & isfinite(lCSV)) = lCSV(badL & isfinite(lCSV));

xref    = 0.5*(xL + xR);
l_minus = xc - xL;
l_plus  = xR - xc;

if isempty(idxLab)
    labelled = zeros(size(zoneIdx));
else
    labelled = tableColNumeric_(T, idxLab);
    labelled(~isfinite(labelled)) = 0;
end

if isempty(idxAcc)
    accepted = 2*ones(size(zoneIdx));
else
    accepted = tableColNumeric_(T, idxAcc);
    accepted(~isfinite(accepted)) = 2;
end

% Sanitise accepted convention.
% 1 = accepted, 0 = rejected, 2 = unlabelled.
accepted(~ismember(accepted,[0 1 2])) = 2;

% If labelled column exists but accepted says 2, honour accepted=2 as unlabelled.
labelled = double(labelled ~= 0);
labelled(accepted == 2) = 0;

raw = [zoneIdx, xL, xc, xR, l, xref, l_minus, l_plus];

[~,base,~] = fileparts(filename);

c = struct();
c.name      = base;
c.filename  = filename;
c.table     = T;
c.raw       = raw;

c.zoneIdx   = zoneIdx;
c.xL        = xL;
c.yL        = yL;
c.xc        = xc;
c.yc        = yc;
c.xR        = xR;
c.yR        = yR;
c.l         = l;
c.xref      = xref;
c.l_minus   = l_minus;
c.l_plus    = l_plus;
c.labelled  = labelled;
c.accepted  = accepted;
end

function headerLine = findTripletHeaderLine_(filename)
% Find the real triplet CSV header line.
%
% Expected header contains at least:
%   zone, x_upstream, x_core, x_downstream

fid = fopen(filename,'r');

if fid < 0
    error('Could not open file: %s', filename);
end

cleaner = onCleanup(@()fclose(fid));

headerLine = [];
lineNo = 0;

while true
    ln = fgetl(fid);

    if ~ischar(ln)
        break;
    end

    lineNo = lineNo + 1;

    % Remove UTF-8 BOM if present.
    if lineNo == 1 && ~isempty(ln)
        ln = regexprep(ln,'^\xEF\xBB\xBF','');
    end

    normLn = lower(ln);
    normLn = regexprep(normLn,'[^a-z0-9_,]','');

    hasZone = contains(normLn,'zone');
    hasXL   = contains(normLn,'x_upstream') || contains(normLn,'xupstream');
    hasXC   = contains(normLn,'x_core')     || contains(normLn,'xcore');
    hasXR   = contains(normLn,'x_downstream') || contains(normLn,'xdownstream');

    if hasZone && hasXL && hasXC && hasXR
        headerLine = lineNo;
        return;
    end
end

error('Could not find triplet CSV header line containing zone, x_upstream, x_core and x_downstream.');
end

function tripletStatsGUI_(caseData)
% GUI that reproduces the MLstructureFinder Feature statistics plots from
% loaded triplet CSV data.

data = caseData.raw;

zoneIdxAll = data(:,1);
l          = data(:,5);
xref       = data(:,6);
l_minus    = data(:,7);
l_plus     = data(:,8);

labelledAll = caseData.labelled(:);
acceptedAll = caseData.accepted(:);

% Defaults match the original featureStatsGUI style.
x0_default       = 0;
xMin_default     = 0;
xMax_default     = inf;
lxMin_default    = 0;
lxMax_default    = inf;
ratioMin_default = 0.125;
ratioMax_default = 8;

fsTick_default  = 10;
fsLabel_default = 12;
fsTitle_default = 12;

nbinsLx_default      = 30;
nbinsRatio_default   = 30;
nbinsJointLx_default = 25;
nbinsJointR_default  = 25;
nbinsLxX_X_default   = 30;
nbinsLxX_L_default   = 30;

xPlotMin_default = xMin_default;

cfg = struct();
cfg.filters = struct('x0',x0_default, ...
                     'xMin',xMin_default, ...
                     'xMax',xMax_default, ...
                     'lxMin',lxMin_default, ...
                     'lxMax',lxMax_default, ...
                     'ratioMin',ratioMin_default, ...
                     'ratioMax',ratioMax_default);

cfg.style = struct('fsTick',fsTick_default, ...
                   'fsLabel',fsLabel_default, ...
                   'fsTitle',fsTitle_default);

cfg.lx    = struct('nbins',nbinsLx_default);
cfg.ratio = struct('nbins',nbinsRatio_default);

cfg.joint = struct('nbinsL',nbinsJointLx_default, ...
                   'nbinsR',nbinsJointR_default);

cfg.lx_x  = struct('nbinsX',nbinsLxX_X_default, ...
                   'nbinsL',nbinsLxX_L_default, ...
                   'xPlotMin',xPlotMin_default, ...
                   'xPlotMax',NaN);

figLx    = [];
figRatio = [];
figJoint = [];
figLxX   = [];

fStats = figure('Name',['Triplet statistics controls — ' caseData.name], ...
                'NumberTitle','off', ...
                'Position',[340 220 940 520]);

pInfo = uipanel('Parent',fStats, ...
                'Title','Loaded case', ...
                'Units','normalized', ...
                'Position',[0.02 0.88 0.96 0.10]);

uicontrol(pInfo,'Style','text', ...
          'String',sprintf('%s   |   %d triplets   |   %d labelled   |   %d accepted   |   %d rejected', ...
              caseData.name, ...
              numel(caseData.zoneIdx), ...
              sum(caseData.labelled == 1), ...
              sum(caseData.accepted == 1), ...
              sum(caseData.accepted == 0)), ...
          'Units','normalized', ...
          'Position',[0.02 0.15 0.96 0.65], ...
          'HorizontalAlignment','left', ...
          'FontSize',10);

pCtrl = uipanel('Parent',fStats, ...
                'Title','Filters', ...
                'Units','normalized', ...
                'Position',[0.02 0.56 0.96 0.30]);

uicontrol(pCtrl,'Style','text','String','x_0:', ...
          'Units','normalized','Position',[0.02 0.65 0.06 0.22], ...
          'HorizontalAlignment','left');

hX0 = uicontrol(pCtrl,'Style','edit','String',num2str(x0_default), ...
          'Units','normalized','Position',[0.08 0.67 0.08 0.24]);

uicontrol(pCtrl,'Style','text','String','x_{min}:', ...
          'Units','normalized','Position',[0.18 0.65 0.08 0.22], ...
          'HorizontalAlignment','left');

hXMin = uicontrol(pCtrl,'Style','edit','String',num2str(xMin_default), ...
          'Units','normalized','Position',[0.26 0.67 0.08 0.24]);

uicontrol(pCtrl,'Style','text','String','x_{max}:', ...
          'Units','normalized','Position',[0.36 0.65 0.08 0.22], ...
          'HorizontalAlignment','left');

hXMax = uicontrol(pCtrl,'Style','edit','String','inf', ...
          'Units','normalized','Position',[0.44 0.67 0.08 0.24]);

uicontrol(pCtrl,'Style','text','String','Subset:', ...
          'Units','normalized','Position',[0.56 0.65 0.08 0.22], ...
          'HorizontalAlignment','left');

hSubset = uicontrol(pCtrl,'Style','popupmenu', ...
          'String',{'All triplets','Accepted only','Rejected only','Labelled only','Unlabelled only'}, ...
          'Units','normalized','Position',[0.64 0.67 0.18 0.24]);

uicontrol(pCtrl,'Style','pushbutton','String','Update plots', ...
          'Units','normalized','Position',[0.84 0.62 0.12 0.30], ...
          'Callback',@(~,~)refreshPlots());

uicontrol(pCtrl,'Style','text','String','(l/(x-x_0))_{min}:', ...
          'Units','normalized','Position',[0.02 0.24 0.18 0.22], ...
          'HorizontalAlignment','left');

hLxMin = uicontrol(pCtrl,'Style','edit','String',num2str(lxMin_default), ...
          'Units','normalized','Position',[0.20 0.26 0.10 0.24]);

uicontrol(pCtrl,'Style','text','String','(l/(x-x_0))_{max}:', ...
          'Units','normalized','Position',[0.32 0.24 0.18 0.22], ...
          'HorizontalAlignment','left');

hLxMax = uicontrol(pCtrl,'Style','edit','String','inf', ...
          'Units','normalized','Position',[0.50 0.26 0.10 0.24]);

uicontrol(pCtrl,'Style','text','String','b/a (min):', ...
          'Units','normalized','Position',[0.62 0.24 0.12 0.22], ...
          'HorizontalAlignment','left');

hRMin = uicontrol(pCtrl,'Style','edit','String',num2str(ratioMin_default), ...
          'Units','normalized','Position',[0.74 0.26 0.08 0.24]);

uicontrol(pCtrl,'Style','text','String','b/a (max):', ...
          'Units','normalized','Position',[0.84 0.24 0.10 0.22], ...
          'HorizontalAlignment','left');

hRMax = uicontrol(pCtrl,'Style','edit','String',num2str(ratioMax_default), ...
          'Units','normalized','Position',[0.93 0.26 0.06 0.24]);

pStyle = uipanel('Parent',fStats, ...
                 'Title','Style (fonts)', ...
                 'Units','normalized', ...
                 'Position',[0.02 0.28 0.46 0.24]);

uicontrol(pStyle,'Style','text','String','Tick font size:', ...
          'Units','normalized','Position',[0.05 0.60 0.30 0.25], ...
          'HorizontalAlignment','left');

hFsTick = uicontrol(pStyle,'Style','edit','String',num2str(fsTick_default), ...
          'Units','normalized','Position',[0.36 0.62 0.20 0.25]);

uicontrol(pStyle,'Style','text','String','Label font size:', ...
          'Units','normalized','Position',[0.05 0.30 0.30 0.25], ...
          'HorizontalAlignment','left');

hFsLabel = uicontrol(pStyle,'Style','edit','String',num2str(fsLabel_default), ...
          'Units','normalized','Position',[0.36 0.32 0.20 0.25]);

uicontrol(pStyle,'Style','text','String','Title font size:', ...
          'Units','normalized','Position',[0.05 0.02 0.30 0.25], ...
          'HorizontalAlignment','left');

hFsTitle = uicontrol(pStyle,'Style','edit','String',num2str(fsTitle_default), ...
          'Units','normalized','Position',[0.36 0.04 0.20 0.25]);

uicontrol(pStyle,'Style','pushbutton','String','Apply style to plots', ...
          'Units','normalized','Position',[0.65 0.20 0.30 0.45], ...
          'Callback',@(~,~)refreshPlots());

pPlot = uipanel('Parent',fStats, ...
                'Title','Plot settings (bins / x-range)', ...
                'Units','normalized', ...
                'Position',[0.50 0.28 0.48 0.24]);

uicontrol(pPlot,'Style','text','String','Bins for l/(x-x_0):', ...
          'Units','normalized','Position',[0.05 0.65 0.30 0.25], ...
          'HorizontalAlignment','left');

hNbinsLx = uicontrol(pPlot,'Style','edit','String',num2str(nbinsLx_default), ...
          'Units','normalized','Position',[0.36 0.67 0.12 0.25]);

uicontrol(pPlot,'Style','text','String','Bins for b/a:', ...
          'Units','normalized','Position',[0.55 0.65 0.35 0.25], ...
          'HorizontalAlignment','left');

hNbinsRatio = uicontrol(pPlot,'Style','edit','String',num2str(nbinsRatio_default), ...
          'Units','normalized','Position',[0.86 0.67 0.10 0.25]);

uicontrol(pPlot,'Style','text','String','Joint l/(x-x_0) vs b/a bins [L,R]:', ...
          'Units','normalized','Position',[0.05 0.35 0.55 0.25], ...
          'HorizontalAlignment','left');

hNbinsJointL = uicontrol(pPlot,'Style','edit','String',num2str(nbinsJointLx_default), ...
          'Units','normalized','Position',[0.62 0.37 0.10 0.25]);

hNbinsJointR = uicontrol(pPlot,'Style','edit','String',num2str(nbinsJointR_default), ...
          'Units','normalized','Position',[0.75 0.37 0.10 0.25]);

uicontrol(pPlot,'Style','text','String','l/(x-x_0) vs x bins [x,l/x]:', ...
          'Units','normalized','Position',[0.05 0.05 0.40 0.25], ...
          'HorizontalAlignment','left');

hNbinsLxX_X = uicontrol(pPlot,'Style','edit','String',num2str(nbinsLxX_X_default), ...
          'Units','normalized','Position',[0.46 0.07 0.10 0.25]);

hNbinsLxX_L = uicontrol(pPlot,'Style','edit','String',num2str(nbinsLxX_L_default), ...
          'Units','normalized','Position',[0.59 0.07 0.10 0.25]);

uicontrol(pPlot,'Style','text','String','x-range for l/(x-x_0) vs x [xmin,xmax]:', ...
          'Units','normalized','Position',[0.72 0.05 0.26 0.25], ...
          'HorizontalAlignment','left');

hXPlotMin = uicontrol(pPlot,'Style','edit','String',num2str(xPlotMin_default), ...
          'Units','normalized','Position',[0.72 0.07 0.10 0.25]);

hXPlotMax = uicontrol(pPlot,'Style','edit','String','', ...
          'Units','normalized','Position',[0.85 0.07 0.10 0.25]);

pActions = uipanel('Parent',fStats, ...
                   'Title','Actions', ...
                   'Units','normalized', ...
                   'Position',[0.02 0.04 0.96 0.18]);

uicontrol(pActions,'Style','pushbutton', ...
          'String','Bring plot windows forward', ...
          'Units','normalized', ...
          'Position',[0.02 0.25 0.20 0.45], ...
          'Callback',@(~,~)bringPlotsForward());

uicontrol(pActions,'Style','text', ...
          'String','The four plot windows update in place. Statistics are printed to the MATLAB console.', ...
          'Units','normalized', ...
          'Position',[0.25 0.20 0.70 0.55], ...
          'HorizontalAlignment','left');

refreshPlots();

    function v = getVal(h, defaultVal)
        str = strtrim(get(h,'String'));

        if isempty(str)
            v = defaultVal;
            set(h,'String',num2str(defaultVal));
            return;
        end

        if strcmpi(str,'inf') || strcmpi(str,'+inf')
            v = inf;
            return;
        end

        v = str2double(str);

        if ~isfinite(v)
            v = defaultVal;

            if isinf(defaultVal)
                set(h,'String','inf');
            else
                set(h,'String',num2str(defaultVal));
            end
        end
    end

    function refreshPlots()
        cfg.filters.x0       = getVal(hX0,   x0_default);
        cfg.filters.xMin     = getVal(hXMin, xMin_default);
        cfg.filters.xMax     = getVal(hXMax, xMax_default);
        cfg.filters.lxMin    = getVal(hLxMin,lxMin_default);
        cfg.filters.lxMax    = getVal(hLxMax,lxMax_default);
        cfg.filters.ratioMin = getVal(hRMin, ratioMin_default);
        cfg.filters.ratioMax = getVal(hRMax, ratioMax_default);

        set(hX0,  'String',num2str(cfg.filters.x0));
        set(hXMin,'String',num2str(cfg.filters.xMin));

        if isfinite(cfg.filters.xMax)
            set(hXMax,'String',num2str(cfg.filters.xMax));
        else
            set(hXMax,'String','inf');
        end

        if isfinite(cfg.filters.lxMax)
            set(hLxMax,'String',num2str(cfg.filters.lxMax));
        else
            set(hLxMax,'String','inf');
        end

        cfg.style.fsTick  = max(1, round(getVal(hFsTick,  fsTick_default)));
        cfg.style.fsLabel = max(1, round(getVal(hFsLabel, fsLabel_default)));
        cfg.style.fsTitle = max(1, round(getVal(hFsTitle, fsTitle_default)));

        set(hFsTick, 'String', num2str(cfg.style.fsTick));
        set(hFsLabel,'String', num2str(cfg.style.fsLabel));
        set(hFsTitle,'String', num2str(cfg.style.fsTitle));

        cfg.lx.nbins     = max(5, round(getVal(hNbinsLx,       nbinsLx_default)));
        cfg.ratio.nbins  = max(5, round(getVal(hNbinsRatio,    nbinsRatio_default)));
        cfg.joint.nbinsL = max(5, round(getVal(hNbinsJointL,   nbinsJointLx_default)));
        cfg.joint.nbinsR = max(5, round(getVal(hNbinsJointR,   nbinsJointR_default)));
        cfg.lx_x.nbinsX  = max(5, round(getVal(hNbinsLxX_X,    nbinsLxX_X_default)));
        cfg.lx_x.nbinsL  = max(5, round(getVal(hNbinsLxX_L,    nbinsLxX_L_default)));

        cfg.lx_x.xPlotMin = getVal(hXPlotMin, xPlotMin_default);

        strXMax = strtrim(get(hXPlotMax,'String'));
        if isempty(strXMax)
            cfg.lx_x.xPlotMax = NaN;
        elseif strcmpi(strXMax,'inf') || strcmpi(strXMax,'+inf')
            cfg.lx_x.xPlotMax = inf;
            set(hXPlotMax,'String','inf');
        else
            tmp = str2double(strXMax);
            if ~isfinite(tmp)
                cfg.lx_x.xPlotMax = NaN;
                set(hXPlotMax,'String','');
            else
                cfg.lx_x.xPlotMax = tmp;
            end
        end

        set(hNbinsLx,     'String',num2str(cfg.lx.nbins));
        set(hNbinsRatio,  'String',num2str(cfg.ratio.nbins));
        set(hNbinsJointL, 'String',num2str(cfg.joint.nbinsL));
        set(hNbinsJointR, 'String',num2str(cfg.joint.nbinsR));
        set(hNbinsLxX_X,  'String',num2str(cfg.lx_x.nbinsX));
        set(hNbinsLxX_L,  'String',num2str(cfg.lx_x.nbinsL));

        denom = xref - cfg.filters.x0;
        lnorm = l ./ denom;
        ratio = l_plus ./ l_minus;

        mask = isfinite(lnorm) & isfinite(ratio) & isfinite(xref) & ...
               isfinite(l) & isfinite(l_minus) & isfinite(l_plus);

        if isfinite(cfg.filters.xMin)
            mask = mask & (xref >= cfg.filters.xMin);
        end

        if isfinite(cfg.filters.xMax)
            mask = mask & (xref <= cfg.filters.xMax);
        end

        if isfinite(cfg.filters.lxMin)
            mask = mask & (lnorm >= cfg.filters.lxMin);
        end

        if isfinite(cfg.filters.lxMax)
            mask = mask & (lnorm <= cfg.filters.lxMax);
        end

        if isfinite(cfg.filters.ratioMin)
            mask = mask & (ratio >= cfg.filters.ratioMin);
        end

        if isfinite(cfg.filters.ratioMax)
            mask = mask & (ratio <= cfg.filters.ratioMax);
        end

        subsetVal = get(hSubset,'Value');

        switch subsetVal
            case 1  % all
                subsetName = 'all triplets';

            case 2  % accepted only
                mask = mask & (acceptedAll == 1);
                subsetName = 'accepted only';

            case 3  % rejected only
                mask = mask & (acceptedAll == 0);
                subsetName = 'rejected only';

            case 4  % labelled only
                mask = mask & (labelledAll == 1);
                subsetName = 'labelled only';

            case 5  % unlabelled only
                mask = mask & (acceptedAll == 2);
                subsetName = 'unlabelled only';

            otherwise
                subsetName = 'all triplets';
        end

        lnormF = lnorm(mask);
        ratioF = ratio(mask);
        xrefF  = xref(mask);
        zoneF  = zoneIdxAll(mask);

        fprintf('\nTriplet statistics for case: %s\n', caseData.name);
        fprintf('Subset: %s\n', subsetName);
        fprintf('Feature stats: %d / %d triplets pass current thresholds.\n', ...
                numel(lnormF), numel(lnorm));

        printScalarStats_('l/(x - x0)', lnormF, zoneF);
        printScalarStats_('b/a', ratioF, zoneF);

        plotLnormPDF();
        plotRatioPDF();
        plotJointLnormRatio();
        plotJointLnormX();

        function plotLnormPDF()
            if isempty(figLx) || ~isvalid(figLx)
                figLx = figure('Name',['PDF of l/(x - x_0) — ' caseData.name], ...
                               'NumberTitle','off');
            end

            figure(figLx);
            clf(figLx);
            ax = axes('Parent',figLx);

            if ~isempty(lnormF)
                histogram(ax, lnormF, cfg.lx.nbins, 'Normalization','pdf');
                xlabel(ax,'l / (x - x_0)');
                ylabel(ax,'PDF');
                title(ax,sprintf('PDF of l / (x - x_0) — %s',subsetName), ...
                      'Interpreter','none');

                if isfinite(cfg.filters.lxMin) && isfinite(cfg.filters.lxMax)
                    xlim(ax,[cfg.filters.lxMin cfg.filters.lxMax]);
                end

                grid(ax,'on');
                box(ax,'on');
                applyStyle_(ax, cfg.style);
            else
                noSamples_(ax);
            end
        end

        function plotRatioPDF()
            if isempty(figRatio) || ~isvalid(figRatio)
                figRatio = figure('Name',['PDF of b/a — ' caseData.name], ...
                                  'NumberTitle','off');
            end

            figure(figRatio);
            clf(figRatio);
            ax = axes('Parent',figRatio);

            if ~isempty(ratioF)
                histogram(ax, ratioF, cfg.ratio.nbins, 'Normalization','pdf');
                xlabel(ax,'b/a');
                ylabel(ax,'PDF');
                title(ax,sprintf('PDF of b/a — %s',subsetName), ...
                      'Interpreter','none');

                if isfinite(cfg.filters.ratioMin) && isfinite(cfg.filters.ratioMax)
                    xlim(ax,[cfg.filters.ratioMin cfg.filters.ratioMax]);
                end

                grid(ax,'on');
                box(ax,'on');
                applyStyle_(ax, cfg.style);
            else
                noSamples_(ax);
            end
        end

        function plotJointLnormRatio()
            if isempty(figJoint) || ~isvalid(figJoint)
                figJoint = figure('Name',['Joint PDF: l/(x-x_0) vs b/a — ' caseData.name], ...
                                  'NumberTitle','off');
            end

            figure(figJoint);
            clf(figJoint);
            ax = axes('Parent',figJoint);

            if ~isempty(lnormF) && ~isempty(ratioF)
                [N2, edgesL2, edgesR2] = histcounts2(lnormF, ratioF, ...
                                                    [cfg.joint.nbinsL cfg.joint.nbinsR]);

                if any(N2(:))
                    centersL = 0.5*(edgesL2(1:end-1) + edgesL2(2:end));
                    centersR = 0.5*(edgesR2(1:end-1) + edgesR2(2:end));

                    [XL, YR] = meshgrid(centersL, centersR);

                    P2 = N2';
                    P2 = P2 / sum(P2(:));

                    surf(ax, XL, YR, P2);
                    shading(ax,'interp');

                    xlabel(ax,'l / (x - x_0)');
                    ylabel(ax,'b/a');
                    zlabel(ax,'Probability');
                    title(ax,sprintf('Joint PDF: l/(x-x_0) vs b/a — %s',subsetName), ...
                          'Interpreter','none');

                    view(ax,35,30);
                    grid(ax,'on');
                    box(ax,'on');
                    applyStyle_(ax, cfg.style);
                else
                    noSamples_(ax);
                end
            else
                noSamples_(ax);
            end
        end

        function plotJointLnormX()
            if isempty(figLxX) || ~isvalid(figLxX)
                figLxX = figure('Name',['Joint PDF: l/(x-x_0) vs x — ' caseData.name], ...
                                'NumberTitle','off');
            end

            figure(figLxX);
            clf(figLxX);
            ax = axes('Parent',figLxX);

            if ~isempty(lnormF) && ~isempty(xrefF)
                xUse = xrefF;
                lUse = lnormF;

                if isfinite(cfg.lx_x.xPlotMin)
                    idx = xUse >= cfg.lx_x.xPlotMin;
                    xUse = xUse(idx);
                    lUse = lUse(idx);
                end

                if isfinite(cfg.lx_x.xPlotMax)
                    idx = xUse <= cfg.lx_x.xPlotMax;
                    xUse = xUse(idx);
                    lUse = lUse(idx);
                end

                if numel(xUse) > 0
                    [N2, edgesX, edgesL] = histcounts2(xUse, lUse, ...
                                                       [cfg.lx_x.nbinsX cfg.lx_x.nbinsL]);

                    if any(N2(:))
                        centersX = 0.5*(edgesX(1:end-1) + edgesX(2:end));
                        centersL = 0.5*(edgesL(1:end-1) + edgesL(2:end));

                        [XX, LL] = meshgrid(centersX, centersL);

                        P2 = N2';
                        P2 = P2 / sum(P2(:));

                        surf(ax, XX, LL, P2);
                        shading(ax,'interp');

                        xlabel(ax,'x');
                        ylabel(ax,'l / (x - x_0)');
                        zlabel(ax,'Probability');
                        title(ax,sprintf('Joint PDF: l/(x-x_0) vs x — %s',subsetName), ...
                              'Interpreter','none');

                        view(ax,35,30);
                        grid(ax,'on');
                        box(ax,'on');
                        applyStyle_(ax, cfg.style);
                    else
                        noSamples_(ax);
                    end
                else
                    text(ax,0.5,0.5,'No samples in x-range', ...
                         'HorizontalAlignment','center', ...
                         'VerticalAlignment','middle');
                    axis(ax,'off');
                end
            else
                noSamples_(ax);
            end
        end
    end

    function bringPlotsForward()
        figs = [figLx figRatio figJoint figLxX];

        for kk = 1:numel(figs)
            if ~isempty(figs(kk)) && isvalid(figs(kk))
                figure(figs(kk));
            end
        end

        figure(fStats);
    end
end


function printScalarStats_(name, vals, zoneF)
if isempty(vals)
    fprintf('  %s: no samples after thresholds.\n', name);
    return;
end

mu  = mean(vals,'omitnan');
sig = std(vals,'omitnan');

[N, edges] = histcounts(vals, 30);

if any(N)
    [~, iMax] = max(N);
    mpv = 0.5*(edges(iMax) + edges(iMax+1));
else
    mpv = NaN;
end

fprintf('  %s: mean = %.4g, std = %.4g, most probable ≈ %.4g\n', ...
        name, mu, sig, mpv);

[maxVal, idxMax] = max(vals);

if ~isempty(zoneF) && numel(zoneF) >= idxMax
    fprintf('  Max %s = %.4g in zone %d\n', ...
            name, maxVal, zoneF(idxMax));
else
    fprintf('  Max %s = %.4g\n', name, maxVal);
end
end


function applyStyle_(ax, style)
if ~ishandle(ax)
    return;
end

set(ax,'FontSize',style.fsTick);

xl = get(ax,'XLabel');
yl = get(ax,'YLabel');
zl = get(ax,'ZLabel');
tl = get(ax,'Title');

if ~isempty(xl)
    set(xl,'FontSize',style.fsLabel);
end

if ~isempty(yl)
    set(yl,'FontSize',style.fsLabel);
end

if ~isempty(zl)
    set(zl,'FontSize',style.fsLabel);
end

if ~isempty(tl)
    set(tl,'FontSize',style.fsTitle);
end
end


function noSamples_(ax)
text(ax,0.5,0.5,'No samples', ...
     'HorizontalAlignment','center', ...
     'VerticalAlignment','middle');
axis(ax,'off');
end


function idx = findColumn_(varNames, patterns, required)
if nargin < 3
    required = true;
end

idx = [];

normNames = cellfun(@normaliseName_, varNames, 'UniformOutput', false);
normPat   = cellfun(@normaliseName_, patterns, 'UniformOutput', false);

% First pass: exact normalised match.
for p = 1:numel(normPat)
    hit = find(strcmp(normNames,normPat{p}),1,'first');

    if ~isempty(hit)
        idx = hit;
        return;
    end
end

% Second pass: contains normalised pattern.
for p = 1:numel(normPat)
    hit = find(contains(normNames,normPat{p}),1,'first');

    if ~isempty(hit)
        idx = hit;
        return;
    end
end

% Special handling for accepted column with verbose header.
if any(strcmp(normPat,'accepted')) || any(strcmp(normPat,'accept'))
    hit = find(contains(normNames,'accepted') | contains(normNames,'accept'),1,'first');

    if ~isempty(hit)
        idx = hit;
        return;
    end
end

if required
    error('Could not find required CSV column matching: %s', strjoin(patterns,', '));
end
end


function s = normaliseName_(s)
s = lower(char(s));
s = regexprep(s,'[^a-z0-9]','');
end


function v = tableColNumeric_(T, idx)
name = T.Properties.VariableNames{idx};
x = T.(name);

if isnumeric(x)
    v = double(x);
elseif islogical(x)
    v = double(x);
elseif iscell(x)
    v = str2double(string(x));
elseif isstring(x)
    v = str2double(x);
elseif ischar(x)
    v = str2double(string(x));
else
    try
        v = double(x);
    catch
        v = str2double(string(x));
    end
end

v = v(:);
end


function nameOut = makeUniqueCaseName_(cases, nameIn)
nameOut = nameIn;

if isempty(cases)
    return;
end

existing = cellfun(@(c)c.name, cases, 'UniformOutput', false);

if ~any(strcmp(existing,nameOut))
    return;
end

base = nameIn;
k = 2;

while true
    cand = sprintf('%s_%d',base,k);

    if ~any(strcmp(existing,cand))
        nameOut = cand;
        return;
    end

    k = k + 1;
end
end